Rails.application.routes.draw do
	
  devise_for :users
   
   
    	root to: 'movies#themeindex'


 
  resources :bios, :controllers => {
    :registrations => "users/registrations"
  }
  
  resources :movies do
  	  resources :reviews,except: [:show,:index]
  	end
  get '/pages_tasks' => 'movies#pages_tasks'
       get '/pages_calendar' => 'movies#pages_calendar'
     get '/mailbox_compose' => 'movies#mailbox_compose'
     get '/mailbox_inbox' => 'movies#mailbox_inbox'
get '/mailbox_message' => 'movies#mailbox_message'
            get '/pages_timeline' => 'movies#pages_timeline'
         get '/pages_timeline_simple' => 'movies#pages_timeline_simple'
          get '/pages_address_book' => 'movies#pages_address_book'
          get '/pages_edit_profile' => 'movies#pages_edit_profile'
     get '/pages_invoice' => 'movies#pages_invoice'
 get '/themeindex' => 'movies#themeindex'
  get '/table_basic' => 'movies#table_basic'
    get '/table_datatables' => 'movies#table_datatables'
     get '/table_export' => 'movies#table_export'
        get '/pages_messages' => 'movies#pages_messages'
         get '/pages_profile' => 'movies#pages_profile'
            get '/pages_gallery' => 'movies#pages_gallery'
  get '/alerts_popups' => 'movies#alerts_popups'
     get '/content_table' => 'movies#content_table'
      get '/pages_faq' => 'movies#pages_faq'
     get '/pages_search' => 'movies#pages_search'
  get '/blog_list' => 'movies#blog_list'
 get '/blog_post' => 'movies#blog_post'
get'/lockscreen' => 'movies#lockscreen'
       get '/pages_login' => 'movies#pages_login'
       get '/login_v2' => 'movies#login_v2'
 get '/login_inside' => 'movies#login_inside'
 get '/login_website' => 'movies#login_website'
 get '/login_websitelight' => 'movies#login_websitelight'
    get '/registration' => 'movies#registration'
   get '/registration_login' => 'movies#registration_login'
   get '/forgot_password' => 'movies#forgot_password'
  get '/error_404' => 'movies#error_404'
  get '/error_4042' => 'movies#error_4042'
  get '/error_500' => 'movies#error_500'
get '/boxed' => 'movies#boxed'
get '/nav_toggled' => 'movies#nav_toggled'
get '/nav_toggledhover' => 'movies#nav_toggledhover'
get'/nav_toggleditemhover' => 'movies#nav_toggleditemhover'
get'/nav_top' => 'movies#nav_top'
get'/nav_right' => 'movies#nav_right'
get'/nav_topfixed' => 'movies#nav_topfixed'
get'/nav_custom' => 'movies#nav_custom'
get'/frame_left' => 'movies#frame_left'
get'/frame_right' => 'movies#frame_right'
get'/search_left' => 'movies#search_left'
get'/page_sidebar' => 'movies#page_sidebar'
get'/page_loading' => 'movies#page_loading'
get'/rtl' => 'movies#rtl'
get'/tabbed' => 'movies#tabbed'
get'/custom_header' => 'movies#custom_header'
get'/adaptive_panels' => 'movies#adaptive_panels'
get'/blank' => 'movies#blank'
get'/widgets' => 'movies#widgets'
get'/elements' => 'movies#elements'
get'/buttons' => 'movies#buttons'
get '/panels' => 'movies#panels'
get '/icons' => 'movies#icons'
get '/typography' => 'movies#typography'
get '/portlet' => 'movies#portlet'
get '/sliders' => 'movies#sliders'
get '/lists' => 'movies#lists'
get '/tour' => 'movies#tour'
get '/nestable' => 'movies#nestable'
get '/autocomplete' => 'movies#autocomplete'
get '/slide_menu' => 'movies#slide_menu'
get '/one_column' => 'movies#one_column'
get '/two_column' => 'movies#two_column'
get '/form_tabbed' => 'movies#form_tabbed'
get '/seperated' => 'movies#seperated'
get '/form_elements' => 'movies#form_elements'
get '/form_validation' => 'movies#form_validation'
get '/form_wizards' => 'movies#form_wizards'
get '/form_editors' => 'movies#form_editors'
get '/form_filehandling' => 'movies#form_filehandling'
get '/charts_morris' => 'movies#charts_morris'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
