# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bfb561960ab766229fa837b039dafe1448fd5328d5782d308e30ecabbdea948abeaedb3981ec5117551c42618d0de3c7266ac290e68e2762a95f68a8a9e8f46

test:
  secret_key_base: 6fc3f4eb45bfbd8d627dca7b136ca9eaa4a88cf5ca2a07081b8312ac542e5f0c78cce4ec50e873ec47a1e8677e9ddf34a348df4140848513de88e86bda0ed625

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
